load_data: True
processed_data: data_files/haaq_physical_vars.csv
input_vars: ['temperature', '10m_u_component_of_wind', '10m_v_component_of_wind', 'relative_humidity', 'specific_humidity', 'total_precipitation', 'total_cloud_cover']
output_vars: ['NO2', 'SO2', 'SPM', 'RSPM/PM10']
model_dir: './models'
job_name: 'testing'
load_model: False

haaq:
  path: data_files/haaq_5625_era5.csv
  res: 5.625

era5:
  path: gs://weatherbench2/datasets/era5/1959-2023_01_10-wb13-6h-1440x721_with_derived_variables.zarr
  time_start: 01-01-1987
  time_end: 12-31-2014

train:
  time_slice: ['01-01-1987', '12-31-2012']

val:
  time_slice: ['01-01-2013', '12-31-2013']

test:
  time_slice: ['01-01-2014', '12-31-2014']